# Generated by Django 6.1 on 2026-09-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDivulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nicho', models.CharField(max_length=100)),
                ('link_grupo', models.URLField(max_length=500)),
                ('plataforma', models.CharField(default='Facebook', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoValidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('nicho', models.CharField(max_length=100)),
                ('imagem_url', models.URLField(max_length=500)),
                ('link_original', models.URLField(max_length=500)),
                ('link_afiliado', models.URLField(max_length=500)),
                ('prompt_video_ia', models.TextField()),
                ('em_vitrine', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
