# Generated by Django 6.1 on 2026-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovalidado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produtovalidado',
            name='comissao_estimada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtovalidado',
            name='comissao_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produtovalidado',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtovalidado',
            name='vendas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='link_afiliado',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='link_original',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='prompt_video_ia',
            field=models.TextField(blank=True, default=''),
        ),
    ]
