# Generated by Django 6.1 on 2026-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produtovalidado_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=64)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_postagem'],
            },
        ),
    ]
