# Generated by Django 6.1 on 2026-09-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('vendas', models.IntegerField(blank=True, null=True)),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('capturado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Snapshot de vendas',
                'verbose_name_plural': 'Snapshots de vendas',
                'ordering': ['-capturado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='grupodivulgacao',
            options={'ordering': ['nome'], 'verbose_name': 'Grupo de divulgação', 'verbose_name_plural': 'Grupos de divulgação'},
        ),
        migrations.AlterModelOptions(
            name='postregistro',
            options={'ordering': ['-data_postagem'], 'verbose_name': 'Registro de post', 'verbose_name_plural': 'Registros de posts'},
        ),
        migrations.AlterModelOptions(
            name='produtovalidado',
            options={'verbose_name': 'Produto validado', 'verbose_name_plural': 'Produtos validados'},
        ),
        migrations.AddField(
            model_name='produtovalidado',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='grupodivulgacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='grupodivulgacao',
            name='link_grupo',
            field=models.URLField(max_length=500, unique=True, verbose_name='Link do grupo'),
        ),
        migrations.AlterField(
            model_name='grupodivulgacao',
            name='nicho',
            field=models.CharField(max_length=100, verbose_name='Nicho'),
        ),
        migrations.AlterField(
            model_name='grupodivulgacao',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do grupo'),
        ),
        migrations.AlterField(
            model_name='grupodivulgacao',
            name='plataforma',
            field=models.CharField(default='Facebook', max_length=50, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='postregistro',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data da postagem'),
        ),
        migrations.AlterField(
            model_name='postregistro',
            name='item_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ID do item'),
        ),
        migrations.AlterField(
            model_name='postregistro',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='comissao_estimada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comissão estimada (R$)'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='comissao_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='em_vitrine',
            field=models.BooleanField(default=False, verbose_name='Está na vitrine'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL da imagem'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='item_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID do item'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='link_afiliado',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link de afiliado'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='link_original',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link original'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='nicho',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Nicho'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='prompt_video_ia',
            field=models.TextField(blank=True, default='', verbose_name='Prompt de vídeo gerado pela IA'),
        ),
        migrations.AlterField(
            model_name='produtovalidado',
            name='vendas',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Número de vendas'),
        ),
        migrations.AddIndex(
            model_name='postregistro',
            index=models.Index(fields=['item_id', 'data_postagem'], name='idx_item_data'),
        ),
        migrations.AddIndex(
            model_name='produtovalidado',
            index=models.Index(fields=['nicho', 'vendas'], name='idx_nicho_vendas'),
        ),
        migrations.AddIndex(
            model_name='produtovalidado',
            index=models.Index(fields=['atualizado_em'], name='idx_atualizado_em'),
        ),
        migrations.AddConstraint(
            model_name='grupodivulgacao',
            constraint=models.UniqueConstraint(fields=('nome', 'plataforma'), name='uniq_grupo_plataforma'),
        ),
        migrations.AddIndex(
            model_name='snapshotvendas',
            index=models.Index(fields=['item_id', 'capturado_em'], name='idx_snap_item_data'),
        ),
    ]
