# Generated by Django 6.1 on 2026-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_snapshotvendas_alter_grupodivulgacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100, verbose_name='ID do item na Shopee')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('imagem_url', models.URLField(blank=True, max_length=500, verbose_name='URL da imagem')),
                ('link_original', models.URLField(blank=True, max_length=500, verbose_name='Link da oferta na Shopee')),
                ('link_afiliado', models.URLField(blank=True, max_length=500, verbose_name='Link de afiliado')),
                ('plataforma', models.CharField(default='shopee', max_length=30, verbose_name='Plataforma do material')),
                ('prompt', models.TextField(blank=True, default='', verbose_name='Prompt gerado')),
                ('legenda', models.TextField(blank=True, default='', verbose_name='Legenda gerada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Divulgação',
                'verbose_name_plural': 'Divulgações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['item_id', 'criado_em'], name='idx_divulg_item_data')],
            },
        ),
        migrations.CreateModel(
            name='LojaAltaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da loja')),
                ('comissao_maxima', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão máxima (%)')),
                ('tipo', models.CharField(choices=[('xtra', 'XTRA COMMISSION'), ('bonus', 'Bônus')], default='xtra', max_length=20, verbose_name='Tipo')),
                ('link_loja', models.URLField(blank=True, max_length=500, verbose_name='Link da loja')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Loja de alta comissão',
                'verbose_name_plural': 'Lojas de alta comissão',
                'ordering': ['-comissao_maxima'],
                'indexes': [models.Index(fields=['tipo'], name='idx_loja_tipo')],
            },
        ),
    ]
