# Generated by Django 6.1 on 2026-09-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_divulgacao_lojaaltacomissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovalidado',
            name='loja',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Loja vendedora'),
        ),
    ]
