# Generated by Django 6.1 on 2026-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produtovalidado_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100, verbose_name='ID do item')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('imagem_url', models.URLField(blank=True, max_length=500, verbose_name='URL da imagem')),
                ('link_afiliado', models.URLField(blank=True, max_length=500, verbose_name='Link de afiliado')),
                ('legenda', models.TextField(blank=True, default='', verbose_name='Legenda')),
                ('prompt', models.TextField(blank=True, default='', verbose_name='Prompt enviado ao Veo')),
                ('modelo', models.CharField(blank=True, default='', max_length=60, verbose_name='Modelo')),
                ('duracao', models.PositiveSmallIntegerField(default=8, verbose_name='Duração (s)')),
                ('operation_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Operação no Google')),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('pronto', 'Pronto'), ('erro', 'Erro')], db_index=True, default='gerando', max_length=20, verbose_name='Status')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('arquivo', models.CharField(blank=True, default='', max_length=255, verbose_name='Arquivo .mp4')),
                ('custo_estimado_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Custo estimado (US$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
            ],
            options={
                'verbose_name': 'Vídeo gerado',
                'verbose_name_plural': 'Vídeos gerados',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['item_id', 'status'], name='idx_video_item_status')],
            },
        ),
    ]
